// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'button': string;
  'input': string;
  'inputContainer': string;
  'root': string;
  'title': string;
}
export const cssExports: CssExports;
export default cssExports;
